services:
  postgres-db:
    # 使用基于 PG16 的 pgvector 官方镜像
    image: pgvector/pgvector:pg16
    container_name: postgres-db
    restart: always
    environment:
      POSTGRES_USER: your_user
      POSTGRES_PASSWORD: your_password
      POSTGRES_DB: your_db
    ports:
      - "5432:5432"
    volumes:
      - ./pgdata:/var/lib/postgresql/data